import express from "express";
import authRouter from "./authRoutes";
import todoRouter from "./todoRoutes";
import userRouter from "./userRoutes";
import GlobalError from "../middlewares/globalErrorMiddleware";
const router = express.Router();
router.use("/auth", authRouter);
router.use("/todo", todoRouter);
router.use("/user", userRouter);
router.use(GlobalError);
export default router;
